/**
 * Project metadata — for display in the scaffold only.
 */

export const PROJECT_NAME = "CustomerOpsAgent";

export const PROJECT_DESCRIPTION =
  "An AI-powered customer operations agent that demonstrates RAG + workflow-based reasoning for logistics and order management scenarios.";

export const LIMITATIONS = [
  "Demo environment — uses mock data, no real logistics API.",
  "No real order management system connected.",
  "Responses are generated by a deterministic workflow, not a production LLM pipeline.",
];
