/**
 * Project metadata — static display data for the info panel.
 */

export const PROJECT_NAME = "CustomerOpsAgent";

export const PROJECT_TAGLINE =
  "Cross-border e-commerce customer service agent demo with RAG, workflow routing, and fallback.";

export const PROJECT_DESCRIPTION =
  "An AI-powered customer operations agent that demonstrates RAG + workflow-based reasoning for logistics and order management scenarios. Default mode uses mock data; optional real LLM adapter is available.";

export const RELEASE_TAG_DISPLAY = "v1.1.0-demo";

export const CAPABILITIES = [
  "RAG knowledge base retrieval",
  "Mock logistics tool integration",
  "Intent recognition & two-layer routing",
  "Deterministic fallback workflow",
  "Optional real LLM adapter",
  "Citation & evidence tracking",
  "Answer source transparency",
];

export const LIMITATIONS = [
  "Demo environment — uses mock data, no real logistics API.",
  "No real order management system connected.",
  "Responses are generated by a deterministic workflow, not a production LLM pipeline.",
  "No authentication or multi-tenancy.",
  "No streaming or WebSocket support.",
];

export const STATUS_BADGES = [
  { label: "Mock Default", variant: "warning" as const },
  { label: "RAG Enabled", variant: "success" as const },
  { label: "Optional LLM", variant: "info" as const },
  { label: "v1.1.0-demo", variant: "accent" as const },
];
