"""
CustomerOps Agent - LLM Adapter Schemas

Data structures for LLM adapter request/response.
"""

from __future__ import annotations

from pydantic import BaseModel, Field


class LLMMessage(BaseModel):
    """A single message in a chat conversation."""

    role: str = Field(
        ...,
        description="Message role: system, user, or assistant",
    )
    content: str = Field(
        ...,
        description="Message content",
    )


class LLMGenerationRequest(BaseModel):
    """Request for LLM text generation."""

    messages: list[LLMMessage] = Field(
        ...,
        description="Conversation messages",
    )
    temperature: float = Field(
        default=0.2,
        ge=0.0,
        le=2.0,
        description="Sampling temperature",
    )
    max_tokens: int = Field(
        default=800,
        gt=0,
        description="Maximum tokens to generate",
    )


class LLMGenerationResult(BaseModel):
    """Result of LLM text generation."""

    text: str = Field(
        ...,
        description="Generated text",
    )
    provider: str = Field(
        ...,
        description="Provider name: mock, openai_compatible",
    )
    model: str | None = Field(
        None,
        description="Model name used",
    )
    is_real_llm: bool = Field(
        default=False,
        description="Whether this was generated by a real LLM",
    )
    fallback_used: bool = Field(
        default=False,
        description="Whether fallback to mock was used",
    )
    error_reason: str | None = Field(
        None,
        description="Error reason if fallback was triggered",
    )
